# Generated by Django 6.0.5 on 2026-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_time",
            field=models.TimeField(default="18:00:00"),
            preserve_default=False,
        ),
    ]
