# Generated by Django 6.0.5 on 2026-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_players",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
