# Generated by Django 6.0.5 on 2026-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_max_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="announcement",
            field=models.TextField(blank=True, default=""),
        ),
    ]
