# Generated by Django 6.0.5 on 2026-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
